### ISSUE TITLE
Zakano Algorithm

### ISSUE THREAD

**Issue by emilyseibert** [willowtreeapps/wombats-api#330] opened 2017-03-13 15:42 UTC
## BEFORE SUBMITTING AN ISSUE CHECK THE FOLLOWING:
- [X] I checked existing issues.
- [X] This is not a support question (which can be answered on Slack).
- [X] This issue is for the API / Game Engine code base (not [Web Client](https://github.com/willowtreeapps/wombats-web-client), [Lambda](https://github.com/willowtreeapps/wombats-lambda), or [Bots](https://github.com/willowtreeapps/wombats-bots))

## GAMEPLAY REQUEST?

A gameplay request constitutes any feature that would improve or modify the gameplay experience of Wombats. Examples would be, additional actions (i.e. mortar, play dead, etc...), or additional arena elements (i.e. lava, jetpack, etc...).

- Describe the gameplay enhancement you would like to see.
Zakano algorithm should be a real attempt

- Provide details on expected behavior.
Zakano algorithm up to oconn

**Comment by oconn** [comment] 2017-03-22 13:03
Acceptance Criteria: Zakano should now have intelligent behavior.

**Comment by morganedmonds** [comment] 2017-03-23 17:27
After some testing, looks like Zakanos are actively going after food as well as shooting at any obstacles that cross their path. They are not actively going after Wombats. These Zakanos will look pretty silly in a Combat arena. :) 

Anyway, assuming this is the intended behavior, moving to closed.

**Closed by morganedmonds** 2017-03-23 17:27 UTC
Labels: 3, enhancement, QA
